#!/usr/bin/ruby

require 'osx/cocoa'
include OSX
OSX.require_framework 'ScriptingBridge'

def run()
  arrange 'Notes', true, 0 => bounds(16, 38, 530, 780)
  arrange 'iTunes', false, 'iTunes' => bounds(58, 195, 1372, 830)
  arrange 'Twitter', true, 0 => bounds(3407, 558, 378, 578)
  arrange 'Messages', true, 'Buddies' => bounds(3792, 557, 190, 809), 'Messages' => bounds(2580, 880, 930, 545) do |app|
    app.status = 1635148140
    app.services.each do |service|
      service.status = 1635148140 if service.enabled
    end
  end
  arrange 'Skype', true, 'Skype' => bounds(2616, 568, 1042, 743)
  arrange 'firefox', true, '*' => bounds(162, 72, 2006, 1121)
  arrange 'iTerm', true, 0 => bounds(994, 457, 1355, 728)

  #apps.each { |bundle_id| unhide bundle_id }

  sleep 3
  rearrange
end

def unhide(bundle_id)
  return if bundle_id.empty?

  quietly do
    app = SBApplication.applicationWithBundleIdentifier bundle_id
    return unless app
    app.windows.each do |window|
      windows.bounds.x = 0 if windows.bounds.x < 0
      windows.bounds.y = 0 if windows.bounds.y < 0
    end
  end
rescue
  puts "oops: #{bundle_id}"
end

def quietly
  on_hold = [STDOUT, STDERR].collect { |stream| stream.dup }
  streams.each do |stream|
    stream.reopen '/dev/null'
    stream.sync = true
  end
  yield
ensure
  streams.each_with_index do |stream, i|
    stream.reopen on_hold[i]
  end
end

def arrange(name, launch, windows)
  app = app_for name, launch
  return unless app

  @cache ||= []
  @cache << [app, windows]
  resize app, windows

  if block_given?
    yield app
  end

  app
end

def rearrange()
  @cache.each do |(app, windows)|
    resize app, windows
  end
end

def resize(app, wins)
  app_windows = app.windows.reject { |w| w.name == '' }.sort_by { |w| w.bounds.x }
  wins.each do |name, bounds|
    if name.is_a?(Integer)
      windows = app_windows.length > name ? [ app_windows[name] ] : nil
    elsif name == '*'
      windows = app_windows
    else
      windows = app_windows.select { |w| w.name == name }
    end

    if windows
      windows.each do |window|
        window.bounds = bounds unless window.bounds == bounds
        ( window.miniaturized = false ) rescue nil
        ( window.minimized = false ) rescue nil
      end
    end
  end
end

def app_for(name, launch)
  return nil unless launch || is_running?(name)

  app = SBApplication.applicationWithBundleIdentifier(bundle_id_for name)
  puts "Unknown app: #{name}" if app.nil?
  app.activate
  app
end

def bounds(x, y, w, h)
  NSRect.new x, y, w, h
end

def bundle_id_for(name)
  @processes[name.downcase] || @apps[name.downcase]
end

def is_running?(name)
  @processes[name.downcase]
end

def prepare()
  system = SBApplication.applicationWithBundleIdentifier 'com.apple.systemevents'

  @processes = {}
  system.processes.each { |p| @processes[p.name.downcase.to_s] = p.bundleIdentifier }

  @apps = {}
  dirs = [ '/Applications/*.app', '/Applications/*/*.app' ]
  dirs.each do |dir|
    Dir["#{dir}/Contents/Info.plist"].each do |ip|
      matches = ip.match(/\/([^\.\/]+)\.app\//)
      if matches && matches.length > 0
        name = matches[1]
        f = File.new ip
        while ! f.eof?
          line = f.readline.strip
          if line == '<key>CFBundleIdentifier</key>'
            id = f.readline.strip.gsub(/<\/?string>/, '')
            @apps[name.downcase] = id
            next
          end
        end
      end
    end
  end
end

def apps
  system = SBApplication.applicationWithBundleIdentifier 'com.apple.systemevents'
  system.processes.map { |p| p.bundleIdentifier.to_s }
end

prepare
run
