#!/usr/bin/ruby

require 'osx/cocoa'
include OSX
OSX.require_framework 'ScriptingBridge'

def run
  apps.each do |app|
    log app_for(app)
  end
end

def app_for(bundle_id)
  SBApplication.applicationWithBundleIdentifier(bundle_id)
end

def log(app)
  return unless app
  name = app.name rescue return
  puts "----- #{name} -----"
  app.windows.each do |window|
    puts "#{window.name} - #{window.bounds.inspect}"
  end
end

def apps
  system = SBApplication.applicationWithBundleIdentifier 'com.apple.systemevents'
  system.processes.map { |p| p.bundleIdentifier.to_s }
end

STDERR.reopen '/dev/null'
STDERR.sync = true
run
