#!/usr/bin/ruby

require 'osx/cocoa'
include OSX
OSX.require_framework 'ScriptingBridge'

def run
  processes.each do |process|
    log process
  end
end

def app_for(process)
  return unless process.hasScriptingTerminology
  SBApplication.applicationWithBundleIdentifier process.bundleIdentifier.to_s
end

def log(process)
  return if process.backgroundOnly
  puts "[ #{process.name} ]"
  app = app_for process
  if app
    name = app.name rescue return
    app.windows rescue return
    app.windows.each do |window|
      wname = window.name
      wname = '<blank>' unless wname && wname.strip != ''
      puts "  #{wname} - #{window.bounds.inspect}"
    end
  end
  puts
end

def processes
  system = SBApplication.applicationWithBundleIdentifier 'com.apple.systemevents'
  system.processes
end

#STDERR.reopen '/dev/null'
#STDERR.sync = true
run
