#!/usr/bin/env ruby

require 'set'

commits = `git log #{ARGV[0]}`.lines

notes = commits.reduce({}) do |memo, commit|
  re = /(bug|feature|chore|release|hotfix|spike)\/([\w-]+)/
  m = re.match commit
  if m
    type = m[1]
    desc = m[2]
    tracker = nil
    m2 = /^(.*)-([0-9]+)$/.match desc
    if m2
      desc = m2[1]
      tracker = m2[2]
    end
    memo[type] ||= Set.new
    memo[type] << { desc: desc, tracker: tracker }
  end
  memo
end

class String
  def pluralize
    return "#{self}es" if self =~ /[x]$/
    "#{self}s"
  end
end

def tracker_link(tracker_id)
  return "" unless tracker_id
  "([#{tracker_id}](https://www.pivotaltracker.com/story/show/#{tracker_id}))"
end

%w(hotfix feature bug chore spike).each do |type|
  if notes[type]
    puts "### #{type.capitalize.pluralize}"
    notes[type].each do |note|
      puts "* #{note[:desc]} #{tracker_link note[:tracker]}"
    end
    puts ""
  end
end
