#!/usr/bin/ruby

require 'fileutils'

root = '/Volumes/Media/iTunes Media'
all = Dir.glob "#{root}/**/*.{mp3,MP3,wav,m4a,m4v}"
songs = Dir.glob "#{root}/**/*\ 1.{mp3,MP3,wav,m4a,m4v}"
puts "Found #{songs.length} probably dups in #{all.length} total"

count = 0
songs.each do |song|
  ext = File.extname song
  orig = song.sub /\ 1\./, "."
  if song == orig
    puts "Something fucked up! #{song}"
    exit 1
  end
  if File.exists? orig
    count += 1
#puts "FileUtils.mv #{orig} #{orig}.deleteme"
    FileUtils.mv orig, "#{orig}.deleteme"
#puts "FileUtils.mv #{song} #{orig}"
    FileUtils.mv song, orig
  end
end

puts "dups: #{count} out of #{songs.length}, in #{all.length} total"
