#!/bin/bash

SESSION=$USER

seek tmux | grep $SESSION | destroy
seek ssh | grep tail | destroy
seek ssh | grep htop | destroy
sleep 1
tmux -2 new-session -d -s $SESSION

# bottom pane - tailing logs + db stats
tmux new-window -t $SESSION:1 -n 'Stickies'
tmux split-window -v
tmux select-pane -t 1
tmux split-window -h
tmux select-pane -t 1
tmux send-keys "~/bin/tail-stickies-prod" C-m
tmux select-pane -t 2
tmux split-window -v
tmux select-pane -t 2
tmux send-keys "ssh stickies-db -t 'htop -d 5'" C-m
tmux select-pane -t 3
tmux send-keys "ssh stickies-worker1 -t 'htop -d 5'" C-m

# top pane - app server stats
tmux select-pane -t 0
tmux split-window -h
tmux select-pane -t 0
tmux split-window -v
tmux select-pane -t 2
tmux split-window -v

tmux select-pane -t 0
tmux send-keys "ssh stickies-prod1 -t 'htop -d 5'" C-m
tmux select-pane -t 1
tmux send-keys "ssh stickies-prod2 -t 'htop -d 5'" C-m
tmux select-pane -t 2
tmux send-keys "ssh stickies-db -t 'htop -d 5'" C-m
#tmux select-pane -t 3
#tmux send-keys "ssh stickies-prod4 -t 'htop -d 5'" C-m

# attach
tmux -2 attach-session -t $SESSION
