#!/bin/bash

SESSION=$USER

seek tmux | grep $SESSION | destroy
seek ssh | grep tail | destroy
seek ssh | grep htop | destroy
sleep 1
tmux -2 new-session -d -s $SESSION

# tail log files
tmux new-window -t $SESSION:1 -n 'Stickies'
tmux split-window -v
tmux select-pane -t 1
tmux send-keys "~/bin/tail-stickies" C-m

# monitor prod1 and db
tmux select-pane -t 0
tmux split-window -h
tmux select-pane -t 0
tmux send-keys "ssh stickies-prod1 -t 'htop'" C-m
tmux select-pane -t 1
tmux send-keys "ssh stickies-db -t 'htop'" C-m

# attach
tmux -2 attach-session -t $SESSION
