#!/usr/bin/env ruby

def parse(f, n)
  f.readlines.each do |line|
    puts "#{n}: #{line}"
  end
end

threads = (1..3).map do |n|
  Thread.new { IO.popen("ssh stickies-prod#{n} 'tail -f /var/log/stickies.log'") { |f| parse f, n } }
end

threads.each { |t| t.join }
