#!/bin/bash

rm -f /tmp/stickies-prod*.log
ssh stickies-prod1 'tail -F /var/log/stickies.log' > /tmp/stickies-prod1.log &
ssh stickies-prod2 'tail -F /var/log/stickies.log' > /tmp/stickies-prod2.log &
sleep 2
trap 'kill $(jobs -p)' EXIT
tail -F /tmp/stickies-prod*.log
